apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dana-ingress
  namespace: dana
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.dana.ir
        - dana.ir
      secretName: dana-tls
  rules:
    - host: api.dana.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
    - host: dana.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing
                port:
                  number: 3000
